scene.setBackgroundColor(7)
effects.confetti.startScreenEffect()
let myCorg = corgio.create(SpriteKind.Player)
myCorg.updateSprite()
myCorg.verticalMovement()
myCorg.horizontalMovement()
myCorg.follow()
